# # This workflow uses actions that are not certified by GitHub.
# # They are provided by a third-party and are governed by
# # separate terms of service, privacy policy, and support
# # documentation.
# #
# # See https://github.com/r-lib/actions/tree/master/examples#readme for
# # additional example workflows available for the R community.
# 
# on:
# #   workflow_dispatch:
#     #inputs:
#     #  logLevel:
#     #    description: 'Log level'
#     #    required: true
#     #    default: 'warning'
#     #    type: choice
#     #    options:
#     #    - info
#     #    - warning
#     #    - debug
#     #  tags:
#   #      description: 'Test scenario tags'
# #        required: false
#         #type: boolean
#    schedule:
#          - cron: "0 0/8 * * *"
#   
#    workflow_dispatch:
# 
# jobs:
#   generate-data:
#     runs-on: ${{ matrix.config.os }}
# 
#     name: ${{ matrix.config.os }} 
# 
#     strategy:
#       fail-fast: false
#       matrix:
#         config:
#           - {os: ubuntu-latest}
# 
#     env:
#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
# 
#     steps:
#       - uses: actions/checkout@v3
#       
#       - name: Install SSH Key
#         uses: shimataro/ssh-key-action@v2
#         with:
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           known_hosts: unnecessary
# 
#       - name: Adding Known Hosts
#         run: ssh-keyscan -p ${{ secrets.SSH_DO_PORT}} -H ${{ secrets.SSH_DO_HOST }}  >> ~/.ssh/known_hosts
# 
#       - name: Upload file to Digital Ocean
#         run: rsync -avz -e "ssh -p ${{ secrets.SSH_DO_PORT }}" /database/SSL_Database.db ${{ secrets.SSH_DO_USER }}@${{ secrets.SSH_DO_HOST }}:/var/plumber/database/
#       
# 
#  

